# Note that only one of these targets is required

bigquery-dw:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: dw-stalse-01
      dataset: covid # You can also use "schema" here
      threads: [1 or more]
      [<optional_config>](#optional-configurations): <value>